services:
  postgres:
    image: postgres:16
    container_name: payment_analytics_db
    environment:
      POSTGRES_DB: payment_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: payment_analytics_api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: payment_analytics
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    command: >
      sh -c "python sql/loader.py --skip-schema &&
             python ml/fraud_detection.py &&
             python ml/customer_segmentation.py &&
             python ml/sentiment_analysis.py &&
             python ml/forecasting.py &&
             uvicorn api.main:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata:
